### ISSUE TITLE
Send signals to underlying process?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [philippkeller/rexpect#1]
I notice you can send a control character like `<ctrl-c>` for keyboard interrupt, or `<ctrl-d>` for EOF. Is there any way to send a signal like `SIGTERM` or `SIGHUP` (perhaps using a [`nix::sys::signal::Signal`]) to the underlying process? 

An alternative might be adding a method to the `PtySession` which gives you a mutable reference to the underlying `PtyProcess` so you can call `signal()` and friends directly on that.

[`nix::sys::signal::Signal`]: https://docs.rs/nix/0.9.0/nix/sys/signal/enum.Signal.html

**Comment by philippkeller** [comment]
Hi Michael. Sorry for the delay, just got back from my holidays (without internet ;-)), I'll look into this in the next days.

**Comment by philippkeller** [comment]
Ah, the members of PtySession need to be public. Totally forgot about that. I now changed that and pushed to crates.io, so you can do now e.g. this:

```
extern crate rexpect;

use rexpect::spawn;
use rexpect::process::signal;
use rexpect::errors::*;

fn do_sleep() -> Result<()> {
    let mut p = spawn("sleep 999", Some(2000))?;
    p.process.signal(signal::SIGINT)?;
    Ok(())
}


fn main() {
    do_sleep().unwrap_or_else(|e| panic!("ftp job failed with {}", e));
}
```

**Comment by philippkeller** [comment]
Closing this as I believe @Michael-F-Bryan your issue is fixed, right?

**Comment by Michael-F-Bryan** [comment]
Yep. Sorry, I probably should have closed this as solved once I saw your reply about pushing a fix to crates.io.

**Comment by philippkeller** [comment]
no worries. I'm glad there are even people using this crate :-)
