### ISSUE TITLE
Migrate away from Error-Chain

### ISSUE THREAD

**Issue by 0xpr03** [philippkeller/rexpect#36]
Error-Chain seems to be unmaintained or rather not developed any further. Furthermore most people start adopting failure,anyhow and eyre for new errors in applications, which require Sync on errors to allow easier multithreading. Currently error-chain can't and won't have sync errors, requiring some special handling for errors of this library. Thus I recommend migrating to thiserror.

See also https://github.com/rust-lang-nursery/error-chain/issues/240 and https://github.com/wisespace-io/pwned-rs/issues/4 for more info and an attached PR for how one can change this.

This is more or less in support of https://github.com/philippkeller/rexpect/pull/29

**Comment by philippkeller** [comment]
@0xpr03 this sounds good. Error-Chain seemed the best choice when I wrote this, but now there are better options.

As I'm currently "out of Rust", I won't implement this. So if you want you can migrate it over. If it passes tests and the example will still work, I'll merge it.

I guess it will also change the api, so I'll just bump the version to reflect this

**Comment by 0xpr03** [comment]
Isn't #29 exactly what we want then ?

**Comment by philippkeller** [comment]
ah yes, didn't realize this is the same error crate where we have the existing PR for. As I'm not into rust anymore, @0xpr03 would you like to have a look if the PR #29 is good? Unfortunately the contributer was not sure either as the person was new to Rust…

**Comment by 0xpr03** [comment]
Regarding maintainership you may want to add [Rust Bus](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046)
I'd also be willing to help out, but I'm probably not the most proficient with this project, just using it at work.

**Comment by philippkeller** [comment]
@0xpr03 thanks for pointing me to rust bus. I've invited rust bus as maintainer now, let's see what happens!

**Comment by matthiasbeyer** [comment]
Closed in #58
