### ISSUE TITLE
Help with maintainance?

### ISSUE THREAD

**Issue by petreeftime** [philippkeller/rexpect#43]
@philippkeller It seems like this project is not being actively maintained anymore. Would you like help with maintenance or would you prefer that this was forked an maintained by someone else?

**Comment by souze** [comment]
I'm interested in contributing to this tool as well. I'm fine with either way.
I think it would be fine to add me as a maintainer for this repo. I'm not sure how it usually works, but doesn't it make more sense when browsing Github that the "main" repository is the maintained one, rather than one of the forks?

**Comment by matthiasbeyer** [comment]
Hi! I am member of the [rust cli-wg](https://github.com/rust-cli/) and am interested in helping with maintaining this crate (at least passively).

I would like to have the second option that @philippkeller mentioned. Everyone who wants to increase the bus-factor gets access to the repository and possibly rights to publish on crates.io.
Maybe it would be even an option to move the repository to the rust-cli organization (plus giving @petreeftime and @souze access of course), but I would need to check with the other WG members if that's okay.

**Comment by petreeftime** [comment]
Sorry, got a little busy with some other things and this fell off my immediate to do list. I think keeping it here for the time being and getting permission to review/merge/push and manage the crate itself would be great. If we can find a more permanent home for it later on, then we can move it then.

**Comment by philippkeller** [comment]
great, this got some momentum here! I added @petreeftime, @matthiasbeyer and @souze as contributors.
I also added you on crates.io - so you should be able to publish new versions (except @souze , for some reason `cargo owner --add souze` fails with `the remote server responded with an error: could not find user with login "souze"`

**Comment by matthiasbeyer** [comment]
@philippkeller thanks for inviting me!

What am I allowed to do and what am I not allowed to do?
Esp. these points, which I would start to do right now:

- implement github-actions
- implement dependabot
- implement bors

**Comment by philippkeller** [comment]
@matthiasbeyer I was never contributor to a open source github repo. What do you suggest? Are there good "settings" which guarantee a general stableness of a repo?

For me - as I'm out of rust since some times, I would trust you - so just go ahead with the 3 points you mentioned

**Comment by matthiasbeyer** [comment]
> What do you suggest? Are there good "settings" which guarantee a general stableness of a repo?

So here is what I will do now:

- [ ] implement CI via github-actions
- [ ] implement some Linting via github-actions
  - [ ] commit linting (esp. `Signed-off-by` trailer for signing [DCO](https://developercertificate.org/))
  - [ ] cargo checks (deny, clippy, fmt,...)
- [ ] implement dependabot so we maintainers do not have to care about dependency updates
- [ ] bors as a merge-bot, which [helps with merge-skew](https://bors.tech/essay/2017/02/02/pitch/)

I would do bors first, which needs some setting on the repository. I will list all that I find important:

- [ ] Disable squash merges (not required for bors per se, but anyways a good option)
- [ ] Enable branch protection for "master"
  - [ ] With "Require a pull request before merging"
  - [ ] With "Require status checks to pass before merging"
  - [ ] With "bors" as only required status check (this setting will appear as soon as I implement bors and won't be available just yet)
  - [ ] "Require pull request reviews before merging" MUST be unmarked
  - [ ] Required for administrators as well

**Comment by souze** [comment]
> (except @souze , for some reason cargo owner --add souze fails with the remote server responded with an error: could not find user with login "souze"

Try again, it should work now

**Comment by philippkeller** [comment]
nice! I added @souze to crates.io rights, and also added bors as app here for rexpect on github

**Comment by matthiasbeyer** [comment]
@philippkeller feel free to close this. I guess maintenance is cleared now? :smile:

**Comment by philippkeller** [comment]
Absolutely, thanks guys for reviving this 🎉
