### ISSUE TITLE
Replace error-chain with thiserror

### ISSUE THREAD

**Issue by matthiasbeyer** [philippkeller/rexpect#58]
I would like to replace the (seemingly abandoned) `error-chain` dependency with the maintained `thiserror`.

Does anyone object? @petreeftime?

rexpect has a lot of `unwrap()`/`expect()` calls in the codebase, which I would like to review after moving to `thiserror` (and hopefully fix, of course).

**Comment by petreeftime** [comment]
Sounds good to me. error-chain seems deprecated.
